### ISSUE TITLE
Timeout missing for "cloud profiles" menu

### ISSUE THREAD

**Issue by mikhail-yarosh** [JetBrains/teamcity-kubernetes-plugin#31] opened 2018-05-21 09:44 UTC
i have a connected to Teamcity kubernetes cluster.
So trouble is:
1) Remove the cluster
2) try to open root project - > cloud profiles
3) enjoy the timeout missing

**Comment by ekoshkin** [comment] 2018-05-22 11:31
@mikhail-yarosh sorry, i did not understand the idea of the issue
could you please rephrase

**Comment by paksv** [comment] 2018-12-28 12:51
Closed as I was unable to reproduce

**Closed by paksv** 2018-12-28 12:51 UTC
